name: Publish django-guid to PyPI and TestPyPI 📦

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Configure private repository
      run: |
        poetry config repositories.test https://test.pypi.org/legacy/
    - name: Build and publish test-pypi
      run: |
        poetry config pypi-token.test ${{ secrets.test_pypi_password }}
        poetry publish --build --no-interaction --repository test
    - name: Build and publish
      run: |
        poetry config pypi-token.pypi ${{ secrets.pypi_password }}
        poetry publish --build --no-interaction
