name: test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: pip install pre-commit
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - uses: actions/cache@v2
        id: pre-commit-cache
        with:
          path: ~/.cache/pre-commit
          key: key-0
      - run: pre-commit run --all-files
        env:
          SKIP: rst

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
        django-version: [ "3.1.4", "3.2", "4.0" ]
        exclude:
          # Django v4 drops Python 3.7 support
          - django-version: 4.0
            python-version: 3.7
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: actions/cache@v2
        id: poetry-cache
        with:
          path: ~/.local
          key: key-2
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          version: 1.2.0a2
      - uses: actions/cache@v2
        id: cache-venv
        with:
          path: .venv
          key: ${{ hashFiles('**/poetry.lock') }}-3
      - run: |
          pip install virtualenv
          virtualenv .venv
          source .venv/bin/activate
          pip install pip setuptools wheel -U
          poetry install --no-interaction --no-root
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - run: |
          source .venv/bin/activate
          pip install "Django==${{ matrix.django-version }}"
      - name: Run tests
        run: |
          source .venv/bin/activate
          poetry run pytest --cov=django_guid tests/ --cov-report=xml
          poetry run coverage report
      - uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
        if: matrix.python-version == '3.10'
